org.gradle.jvmargs=-Xmx2G -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.configuration-cache=false

minecraft_version=26.1.2
loader_version=0.19.3
loom_version=1.17.17

release_channel=Alpha
mod_version=0.3.9
alpha_iteration=34
maven_group=cloudy.qcloudy
archives_base_name=QCloudy_Addition
